### mypy config (for type-checking)
[mypy]
exclude_gitignore = True
# prefer direct imports, or intentional reexport with `__all__`
implicit_reexport = False
# avoid easily-avoidable dead code (or locate typing errors)
warn_unreachable = True
# prefer types that can be understood by reading code in only one place
local_partial_types = True

# strict/loose: start with strict type-checking; loosen to fit
# see https://mypy.readthedocs.io/en/stable/existing_code.html#introduce-stricter-options
strict = True
## BEGIN possible global loosenings from `strict`:
# disallow_subclassing_any = False
# warn_unused_configs = False
# warn_redundant_casts = False
# warn_unused_ignores = False
# strict_equality = False
# strict_concatenate = False
# check_untyped_defs = False
# disallow_untyped_decorators = False
# disallow_any_generics = False
# disallow_untyped_calls = False
# disallow_incomplete_defs = False
# disallow_untyped_defs = False
# no_implicit_reexport = False
# warn_return_any = False
## END loosenings of `strict`
# (prefer module-specific loosening, when reasonable)


###
# module-specific config

# [mypy-my.example]
# disallow_untyped_defs = False

[mypy-django_shtrove.shtrove_imps.index.*]
disallow_untyped_defs = False
