[project]
name = "django-shtrove"
version = "0.1.0"
description = ""
authors = [
    {name = "abram axel booth",email = "boothaa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # TODO: consider moving src/shtrove/ to separate "shtrove==0.1.0",
    "primitive_metadata @ git+https://github.com/aaxelb/primitive_metadata.git@0.2026.0",
    # "primitive_metadata==0.2026.0",  # MIT
    "rdflib==7.6.0",  # BSD 3 Clause
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3",
]

[project.entry-points."shtrove.ProtoExtract"]
TurtleExtract = "shtrove.imps.extract:TurtleExtract"
# TODO: jsonld =

[project.entry-points."shtrove.ProtoPersist"]
DjangoShtrovePersist = "django_shtrove.shtrove_imps.persist:DjangoShtrovePersist"

[project.entry-points."shtrove.ProtoIndex"]
ShtrovesearchElastic8Index = "django_shtrove.shtrove_imps.index:ShtrovesearchElastic8Index"

[project.entry-points."shtrove.ProtoDerive"]
# TODO: oai_dc? datacite?

[project.entry-points."shtrove.ProtoRender"]
HtmlRender = "shtrove.render.html:HtmlRender"
TurtleRender = "shtrove.render.turtle:TurtleRender"
JsonApiRender = "shtrove.render.jsonapi:JsonApiRender"
JsonLdRender = "shtrove.render.jsonld:JsonLdRender"
ShtrovesearchCsvRender = "shtrove.render.shtrovesearch_csv:ShtrovesearchCsvRender"
ShtrovesearchTsvRender = "shtrove.render.shtrovesearch_tsv:ShtrovesearchTsvRender"
ShtrovesearchJsonRender = "shtrove.render.shtrovesearch_json:ShtrovesearchJsonRender"

[project.entry-points."shtrove.ProtoShtrove"]
# TODO: DjangoShtrove = "django_shtrove...
# TODO: basic shtrove using only filetree, no database or django?

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
  'flake8',
  'mypy',
  'black',
]
test = [
  # TODO: 'coverage',
]

[tool.poetry]
packages = [
  {include = "django_shtrove", from = "src"},
  {include = "shtrove", from = "src"},
]

# [tool.coverage.run]
# source = ['src']
# branch = true
#
# [tool.coverage.report]
# skip_covered = true
# show_missing = true

[tool.black]
target-version = ["py312"]
