"""shtrove.proto: interfaces for shtrove args and returns
"""
import collections.abc as cabc
import typing
import uuid

from primitive_metadata import primitive_rdf as rdf


class ProtoShtroveStrategy(typing.Protocol):
    def way_to_extract(self, mediatype: str) -> ProtoExtractStrategy: ...
    def way_to_persist(self) -> ProtoPersistStrategy: ...
    def each_way_to_derive(self) -> cabc.Iterator[ProtoDeriveStrategy]: ...
    def each_way_to_index(self) -> cabc.Iterator[ProtoIndexStrategy]: ...
    def way_to_render(self, accepts: cabc.Sequence[str] = ()) -> ProtoRenderStrategy: ...
