"""shtrove.types: interfaces for shtrove args and returns
"""
import collections.abc as cabc
import typing

from shtrove.extract.types import ProtoExtract
from shtrove.persist.types import ProtoPersist
from shtrove.derive.types import ProtoDerive
from shtrove.index.types import ProtoIndex
from shtrove.render.types import ProtoRender


class ProtoShtrove(typing.Protocol):
    def __init__(self) -> typing.Self: ...
    def way_to_extract(self, mediatype: str) -> ProtoExtract: ...
    def way_to_persist(self) -> ProtoPersist: ...
    def each_way_to_derive(self) -> cabc.Iterator[ProtoDerive]: ...
    def each_way_to_index(self) -> cabc.Iterator[ProtoIndex]: ...
    def way_to_search(self, name: str = '') -> ProtoIndex: ...
    def way_to_render(self, accepts: cabc.Sequence[str] = ()) -> ProtoRender: ...
