"""shtrove.types: interfaces for shtrove args and returns
"""
import collections.abc as cabc
import typing

from shtrove.extract.types import ProtoExtractStrategy
from shtrove.persist.types import ProtoPersistStrategy
from shtrove.derive.types import ProtoDeriveStrategy
from shtrove.index.types import ProtoIndexStrategy
from shtrove.render.types import ProtoRenderStrategy


class ProtoShtroveStrategy(typing.Protocol):
    def way_to_extract(self, mediatype: str) -> ProtoExtractStrategy: ...
    def way_to_persist(self) -> ProtoPersistStrategy: ...
    def each_way_to_derive(self) -> cabc.Iterator[ProtoDeriveStrategy]: ...
    def each_way_to_index(self) -> cabc.Iterator[ProtoIndexStrategy]: ...
    def way_to_search(self, name: str = '') -> ProtoIndexStrategy: ...
    def way_to_render(self, accepts: cabc.Sequence[str] = ()) -> ProtoRenderStrategy: ...
