name: check_django_shtrove

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        id: setup-py
        with:
          python-version: '3.13'
      - run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13', '3.14']
        django: ['4.2', '5.1', '5.2']
    services:
      postgres18:
        image: postgres:18
        environment:
          POSTGRES_DB: shtrove
          POSTGRES_HOST_AUTH_METHOD: trust  # no security
      elasticsearch8:
        image: elasticsearch:8.19.11
        ports:
          - 9208:9200
        env:
          xpack.security.enabled: false
          node.name: singlenode
          cluster.initial_master_nodes: singlenode
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        id: setup-py
        with:
          python-version: ${{ matrix.python }}
      - run: make test
        env:
          ELASTICSEARCH8_URL: http://localhost:9208
